dist:     xenial
language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on GOFLAGS=-mod=vendor LIBVIRT_DEFAULT_URI='qemu+unix:///session' TF_LIBVIRT_DISABLE_PRIVILEGED_TESTS=1 TF_LIBVIRT_RNG_DEV='/dev/random'
git:
  depth: 1
before_script:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.0/terraform_0.12.0_linux_amd64.zip
  - sudo unzip /tmp/terraform.zip -d /usr/local/bin
  - sudo bash ./travis/setup-host
addons:
  apt:
    packages:
    - libvirt-dev
    - libvirt-daemon
    - qemu-system-x86
    - qemu-utils
    - genisoimage
    - xsltproc
script:
  - for n in $(seq 10); do env TF_LOG=DEBUG make testacc TEST_ARGS="-run TestAccLibvirtVolume_RepeatedName"; done
